################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lvgl/src/lv_themes/lv_theme.c \
../lvgl/src/lv_themes/lv_theme_alien.c \
../lvgl/src/lv_themes/lv_theme_default.c \
../lvgl/src/lv_themes/lv_theme_material.c \
../lvgl/src/lv_themes/lv_theme_mono.c \
../lvgl/src/lv_themes/lv_theme_nemo.c \
../lvgl/src/lv_themes/lv_theme_night.c \
../lvgl/src/lv_themes/lv_theme_templ.c \
../lvgl/src/lv_themes/lv_theme_zen.c 

OBJS += \
./lvgl/src/lv_themes/lv_theme.o \
./lvgl/src/lv_themes/lv_theme_alien.o \
./lvgl/src/lv_themes/lv_theme_default.o \
./lvgl/src/lv_themes/lv_theme_material.o \
./lvgl/src/lv_themes/lv_theme_mono.o \
./lvgl/src/lv_themes/lv_theme_nemo.o \
./lvgl/src/lv_themes/lv_theme_night.o \
./lvgl/src/lv_themes/lv_theme_templ.o \
./lvgl/src/lv_themes/lv_theme_zen.o 

C_DEPS += \
./lvgl/src/lv_themes/lv_theme.d \
./lvgl/src/lv_themes/lv_theme_alien.d \
./lvgl/src/lv_themes/lv_theme_default.d \
./lvgl/src/lv_themes/lv_theme_material.d \
./lvgl/src/lv_themes/lv_theme_mono.d \
./lvgl/src/lv_themes/lv_theme_nemo.d \
./lvgl/src/lv_themes/lv_theme_night.d \
./lvgl/src/lv_themes/lv_theme_templ.d \
./lvgl/src/lv_themes/lv_theme_zen.d 


# Each subdirectory must supply rules for building sources it contributes
lvgl/src/lv_themes/lv_theme.o: ../lvgl/src/lv_themes/lv_theme.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32 -DSTM32F746xx -DSTM32F746NGHx '-D__packed=__attribute__((__packed__))' -DSTM32F7 -DSTM32F746G_DISCO -DDEBUG '-D__weak=__attribute__((weak))' -c -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/hal_stm_lvgl" -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Utilities/STM32746G-Discovery" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Include" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/nesat/Documents/GitHub/lv_port_stm32f746_disco_atollic - Kopya" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I../Inc -I../Drivers/CMSIS/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/lvgl" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lvgl/src/lv_themes/lv_theme.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lvgl/src/lv_themes/lv_theme_alien.o: ../lvgl/src/lv_themes/lv_theme_alien.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32 -DSTM32F746xx -DSTM32F746NGHx '-D__packed=__attribute__((__packed__))' -DSTM32F7 -DSTM32F746G_DISCO -DDEBUG '-D__weak=__attribute__((weak))' -c -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/hal_stm_lvgl" -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Utilities/STM32746G-Discovery" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Include" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/nesat/Documents/GitHub/lv_port_stm32f746_disco_atollic - Kopya" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I../Inc -I../Drivers/CMSIS/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/lvgl" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lvgl/src/lv_themes/lv_theme_alien.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lvgl/src/lv_themes/lv_theme_default.o: ../lvgl/src/lv_themes/lv_theme_default.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32 -DSTM32F746xx -DSTM32F746NGHx '-D__packed=__attribute__((__packed__))' -DSTM32F7 -DSTM32F746G_DISCO -DDEBUG '-D__weak=__attribute__((weak))' -c -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/hal_stm_lvgl" -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Utilities/STM32746G-Discovery" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Include" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/nesat/Documents/GitHub/lv_port_stm32f746_disco_atollic - Kopya" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I../Inc -I../Drivers/CMSIS/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/lvgl" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lvgl/src/lv_themes/lv_theme_default.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lvgl/src/lv_themes/lv_theme_material.o: ../lvgl/src/lv_themes/lv_theme_material.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32 -DSTM32F746xx -DSTM32F746NGHx '-D__packed=__attribute__((__packed__))' -DSTM32F7 -DSTM32F746G_DISCO -DDEBUG '-D__weak=__attribute__((weak))' -c -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/hal_stm_lvgl" -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Utilities/STM32746G-Discovery" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Include" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/nesat/Documents/GitHub/lv_port_stm32f746_disco_atollic - Kopya" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I../Inc -I../Drivers/CMSIS/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/lvgl" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lvgl/src/lv_themes/lv_theme_material.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lvgl/src/lv_themes/lv_theme_mono.o: ../lvgl/src/lv_themes/lv_theme_mono.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32 -DSTM32F746xx -DSTM32F746NGHx '-D__packed=__attribute__((__packed__))' -DSTM32F7 -DSTM32F746G_DISCO -DDEBUG '-D__weak=__attribute__((weak))' -c -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/hal_stm_lvgl" -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Utilities/STM32746G-Discovery" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Include" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/nesat/Documents/GitHub/lv_port_stm32f746_disco_atollic - Kopya" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I../Inc -I../Drivers/CMSIS/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/lvgl" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lvgl/src/lv_themes/lv_theme_mono.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lvgl/src/lv_themes/lv_theme_nemo.o: ../lvgl/src/lv_themes/lv_theme_nemo.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32 -DSTM32F746xx -DSTM32F746NGHx '-D__packed=__attribute__((__packed__))' -DSTM32F7 -DSTM32F746G_DISCO -DDEBUG '-D__weak=__attribute__((weak))' -c -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/hal_stm_lvgl" -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Utilities/STM32746G-Discovery" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Include" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/nesat/Documents/GitHub/lv_port_stm32f746_disco_atollic - Kopya" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I../Inc -I../Drivers/CMSIS/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/lvgl" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lvgl/src/lv_themes/lv_theme_nemo.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lvgl/src/lv_themes/lv_theme_night.o: ../lvgl/src/lv_themes/lv_theme_night.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32 -DSTM32F746xx -DSTM32F746NGHx '-D__packed=__attribute__((__packed__))' -DSTM32F7 -DSTM32F746G_DISCO -DDEBUG '-D__weak=__attribute__((weak))' -c -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/hal_stm_lvgl" -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Utilities/STM32746G-Discovery" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Include" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/nesat/Documents/GitHub/lv_port_stm32f746_disco_atollic - Kopya" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I../Inc -I../Drivers/CMSIS/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/lvgl" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lvgl/src/lv_themes/lv_theme_night.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lvgl/src/lv_themes/lv_theme_templ.o: ../lvgl/src/lv_themes/lv_theme_templ.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32 -DSTM32F746xx -DSTM32F746NGHx '-D__packed=__attribute__((__packed__))' -DSTM32F7 -DSTM32F746G_DISCO -DDEBUG '-D__weak=__attribute__((weak))' -c -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/hal_stm_lvgl" -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Utilities/STM32746G-Discovery" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Include" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/nesat/Documents/GitHub/lv_port_stm32f746_disco_atollic - Kopya" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I../Inc -I../Drivers/CMSIS/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/lvgl" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lvgl/src/lv_themes/lv_theme_templ.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lvgl/src/lv_themes/lv_theme_zen.o: ../lvgl/src/lv_themes/lv_theme_zen.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32 -DSTM32F746xx -DSTM32F746NGHx '-D__packed=__attribute__((__packed__))' -DSTM32F7 -DSTM32F746G_DISCO -DDEBUG '-D__weak=__attribute__((weak))' -c -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/hal_stm_lvgl" -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Utilities/STM32746G-Discovery" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Include" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/nesat/Documents/GitHub/lv_port_stm32f746_disco_atollic - Kopya" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I../Inc -I../Drivers/CMSIS/Include -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/lvgl" -I"C:/Users/nesat/STM32CubeIDE/workspace_1.0.1/LEDCONTROLLER/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy" -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lvgl/src/lv_themes/lv_theme_zen.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

